default: &default
  adapter: postgresql
  encoding: unicode
  user: 'web'
  password: '123'
  host: 'localhost'
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_development

test:
  <<: *default
  database: rails_test

production:
  <<: *default
  database: first_production
